name: Build and deploy hugo page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # https://github.com/peaceiris/actions-hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.139.4'
          extended: true

      - name: Build
        run: hugo --minify

      # https://github.com/marketplace/actions/ftp-deploy
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: cc1.ccnode.org
          username: web111_blog
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          protocol: ftps
